alias: L2 Segment 1 On
description: "500W "
trigger:
  - type: power
    platform: device
    device_id: 529577b31c2d2aa0e99d5e43fe70b4f4
    entity_id: sensor.l2_power
    domain: sensor
    below: 500
condition: []
action:
  - type: turn_on
    device_id: 3bd5eca31fcf739eb0c854436538b786
    entity_id: 21ffb0f915a3a462cd131578d3a183b1
    domain: light
  - service: light.turn_on
    target:
      entity_id: 21ffb0f915a3a462cd131578d3a183b1
    data_template:
      rgb_color: >-
        {% if states('sensor.rounded_nordpool_value')|float <= 0.5 %}
          [0, 128, 0]
        {% elif states('sensor.rounded_nordpool_value')|float > 0.5 and
        states('sensor.rounded_nordpool_value')|float <= 1 %}
          [{{ (128*(states('sensor.rounded_nordpool_value')|float-0.5))|int }}, 128, 0]
        {% elif states('sensor.rounded_nordpool_value')|float > 1 and
        states('sensor.rounded_nordpool_value')|float <= 1.5 %}
          [128, {{ (128*(1.5-states('sensor.rounded_nordpool_value')|float))|int }}, 0]
        {% else %}
          [128, 0, 0]
        {% endif %}
mode: single
